### ISSUE TITLE
Use `Sandbox.ClothingContainer` for clothes.

### ISSUE THREAD

**Issue by kolexxx** [sbox-TTT/TTT#149]
Switch to `Sandbox.ClothingContainer` instead of having our own clothing system. Also make the detective hat a clothing resource. An added bonus from this is that people can switch to using their own avatars thanks to `LoadFromClient( Client cl )`.

**Comment by mzegar** [comment]
Allow people to use their own avatars, but this should be `disabled` by default 🤯

**Comment by mzegar** [comment]
https://github.com/sbox-TTT/TTT/pull/161
