### ISSUE TITLE
Role picking RNG is broken

### ISSUE THREAD

**Issue by KingOfTheFBI** [sbox-TTT/TTT#193]
The role picking will constantly pick the same person over and over again. Something is up with the RNG

**Comment by mzegar** [comment]
Yeah we should do some proper testing and make sure this works. I think it's always been broken.

**Comment by the-remeko** [comment]
My pull request https://github.com/sbox-TTT/TTT/pull/196 should fix this (assuming KingOfTheFBI was only experiencing this with a low player count).

**Comment by mzegar** [comment]
I just uploaded @the-remeko changes, if you notice it picking a single player constantly re-open this issue @KingOfTheFBI
