### ISSUE TITLE
Whitelist / Blacklist maps

### ISSUE THREAD

**Issue by mzegar** [sbox-TTT/TTT#203]
@kolexxx Maybe we should provide a way for server owners to whitelist/blacklist of maps in a file server

**Comment by KingOfTheFBI** [comment]
Would be a really good addition

**Comment by mzegar** [comment]
https://github.com/sbox-TTT/TTT/pull/208

**Comment by mzegar** [comment]
https://github.com/sbox-TTT/TTT/commit/93d23d2deec9cfd28aa042e3499237dc9f64726d
