### ISSUE TITLE
Shop Menu / Role Menu Refactor

### ISSUE THREAD

**Issue by matekdev** [sbox-TTT/TTT#213]
1. We need a new design for the shop menu (radial or grid)
2. We should show gylphs for each tab, and let people switch tabs with the number keys

**Comment by mzegar** [comment]
![image](https://user-images.githubusercontent.com/32153021/187555183-4f3274e8-14ec-48ff-a194-792ab87d9f49.png)
"The ideal grid menu"

**Comment by matekdev** [comment]
What we have is good enough for a while now.
