### ISSUE TITLE
Gun Sounds Need Equalization

### ISSUE THREAD

**Issue by ndo360** [sbox-TTT/TTT#221]
Greetings.

One thing I noticed was how the gun sounds vary in loudness from gun to gun with no consistency on the peak volume. When you shoot the M9 pistol for example it sounds quite muffled, but on the other hand shooting the AK47 is ear piecing. Adjusting your in-game volume to account for the louder guns just muffles and silences the other more quieter guns with a lower peak volume.

I think all guns, explosions, and anything loud in general be equalized. That way when one adjusts their volume for their game it impacts everything equally. (Some have exclusions of course, like using a suppressed pistol and such.)

P.S. It would be kinda funny if the M9 is using the suppressed pistol's sound file instead, which lead to this misconception, but I doubt it.

**Comment by matekdev** [comment]
I tuned some of the values, let me know if there are any others you think need to be changed.

**Comment by ndo360** [comment]
It's fixed. Thanks.
