### ISSUE TITLE
3D Gun Audio Reaches "Uncanny Valley"

### ISSUE THREAD

**Issue by ndo360** [sbox-TTT/TTT#225]
Greetings.

I have discovered that while firing weapons it seems to take a "3D" effect and favors the right audio channel. I am unsure if this is intentional, but it seems to give off the "Uncanny Valley" type feeling while shooting. Mainly that it feels... wrong. Mainly as it leaves the left audio channel feel underused, or at worst gives a muted impression.

This effect is made worse if wearing a headset with the ability to hot-switch between 7.1 Surround Sound. (I personally have a HyperX headset and with 7.1 Surround Sound disabled it makes the jarring effect more apparent.)

Has anyone else had this feeling about the gun sound effects?

**Comment by matekdev** [comment]
Can you check if this happens on other s&box gamemodes? If so it's not our issue.

**Comment by ndo360** [comment]
I'll double check.

**Comment by ndo360** [comment]
Just confirmed in base S&Box mode, with their pistol, that it doesn't have the same uncanny effect.

To highlight the effect I am talking about in TTT do the following:
In-game grab the revolver, crouch, and move left and right as you shoot. You will notice how the audio floats around.

**Comment by the-remeko** [comment]
I'm gonna take a look at this.

**Comment by the-remeko** [comment]
https://github.com/sbox-TTT/TTT/pull/227 should fix this.
